# Generated by Django 3.2.25 on 2026-09-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20260910_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretour',
            name='dumble',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AjustementDumble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.listejoueurs')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustements_dumble', to='score.partie')),
            ],
        ),
    ]
